### ISSUE TITLE
feature: site title and link in brand logo

### ISSUE THREAD

**Issue by gcsandesh** [ojasaklechayt/Reslink-Dashboard#14]
I would like to change the site title from "Vite + React" to "Reslink Dashboard"
And, I would like to add link to the Reslink logo in the left side bar.

![image](https://github.com/ojasaklechayt/Reslink-Dashboard/assets/59115123/55dc0179-5091-441e-8df7-b0d8674ba400)

Please assign this issue to me under hacktoberfest.

**Comment by ojasaklechayt** [comment]
Go for it
