### ISSUE TITLE
Add notifications menu

### ISSUE THREAD

**Issue by ImZaryab** [ojasaklechayt/Reslink-Dashboard#17]
## What
Adding a drop down notifications menu.
## Why?
- Create user interaction.
- Hactoberfest contribution.
## Screenshot
![image](https://github.com/ojasaklechayt/Reslink-Dashboard/assets/75939775/f1f1f3e3-a5ed-4dad-85c3-8ad8f27847cb)
## Extras
Kindly assign the appropriate hacktoberfest labels.

**Comment by aneekamangal07** [comment]
kindly assign this issue to me, i would like to contribute

**Comment by ojasaklechayt** [comment]
I feel notification is not responsive.
![image](https://github.com/ojasaklechayt/Reslink-Dashboard/assets/90605717/11e62a81-e2a4-4559-8f5c-00083df475a8)
Please check into it
@ImZaryab
