### ISSUE TITLE
Write methods in CONTRIBUTION.md 

### ISSUE THREAD

**Issue by ojasaklechayt** [ojasaklechayt/Reslink-Dashboard#4]
- Write method to folk the repo
- Write method clone the folked repo
- Write method to install the dependencies i.e. npm install
- Also mention about the hacktoberfest guideline issue i.e. #1

**Comment by adarsht0001** [comment]
is it still open and can u provide more details

**Comment by ojasaklechayt** [comment]
> is it still open and can u provide more details

Hey Adarsh, So I am looking to add more information in CONTRIBUTION.md. Like add git bash syntaxes for cloning the repo, forking the repo and installing the dependencies

**Comment by adarsht0001** [comment]
i have created a pr for that can please let me know any edits is needed

**Comment by ojasaklechayt** [comment]
> i have created a pr for that can please let me know any edits is needed

No changes needed Thanks for the contribution Adarsh
