### ISSUE TITLE
Chore: upgrade README.md

### ISSUE THREAD

**Issue by Ronit-gurjar** [ojasaklechayt/Reslink-Dashboard#6]
**hey** @ojasaklechayt ✌️

I think this project is Great in terms of UI. I think it's time to upgrade the `README.md` for better understanding of the project as well as make this repo look COOL🔥.

> if you like the idea please assign this issue to me and consider adding `hacktoberfest` tag

**Comment by ojasaklechayt** [comment]
@Ronit-gurjar do you want to work on this issue ? I can assign you this

**Comment by Ronit-gurjar** [comment]
Yes please, I'd be glad to contribute 🔥
