### ISSUE TITLE
Fix: Search bar in mobile view

### ISSUE THREAD

**Issue by Ronit-gurjar** [ojasaklechayt/Reslink-Dashboard#9]
hey @ojasaklechayt 🔥

Found this little bug on the Mobile view : -

![image](https://github.com/ojasaklechayt/Reslink-Dashboard/assets/92150685/cd181dc6-4760-4d5d-af70-682bf112aff4)

` Suggestion : ` Replace the search bar with just a search icon with black background, which sh0uld look somewhat like this

![image](https://github.com/ojasaklechayt/Reslink-Dashboard/assets/92150685/4240ce1b-9ac3-4f99-a2a6-0dd156972e58)

**Comment by ojasaklechayt** [comment]
@Ronit-gurjar can you fix it ?

**Comment by Ronit-gurjar** [comment]
Well, let me see what i can🔥pls assign to me

**Comment by ojasaklechayt** [comment]
@Ronit-gurjar Done
